Repository Keepingshtum/CS146, pull requests merged in 2024-05, with the labels that each got.

#87 [Lab][Lab5] - Recursion Solution - [Patricio Gonzalez]
  Labs/Lab5/Lab5_recursion.java
  Labs/Lab5/Lab5_recursion.py
  Labs/Lab5/Lab5_recursion.txt
Labels: EC Approved

#89 [Labs][Lab6] - Python DFS Solution - [Justin Nguyen]
  Labs/Lab 6/Lab6PythonDFSSolution.py
Labels: EC Approved

#94 [HW][HW7] - Java Greedy Solution - [Justin Nguyen]
  HW/HW7/HW7JavaGreedySolution.java
Labels: EC Approved

#114 [LABS][LAB7] - python variation of warshall Solution - [James Altizer]lab7v2.py
  Labs/Lab7/lab7v2.py
Labels: EC Approved

#117 [HW][HW10] - Pseudocode Queue Solution - [Alejandro Pacheco]
  HW/HW10/HW10 PseudocodeQueue.txt
Labels: EC Approved

#126 [ENHANCEMENT] Issue #48 Compressed Notes/Compendium Creation
  Compendium/Algorithms/All-pairs shortest path/Floyd-Warshall Algorithm
  Compendium/Algorithms/All-pairs shortest path/Johnson's Algorithm
  Compendium/Algorithms/Graph Traversal/Breadth-First Search
  Compendium/Algorithms/Graph Traversal/Depth-First Search
  Compendium/Algorithms/Minimum Spanning Tree (MST)/Boruvka's Algorithm
  Compendium/Algorithms/Minimum Spanning Tree (MST)/Kruskal's Algorithm
  Compendium/Algorithms/Minimum Spanning Tree (MST)/Prim's Algorithm
  Compendium/Algorithms/Single-source shortest path/A*
  Compendium/Algorithms/Single-source shortest path/Bellman-Ford Algorithm
  Compendium/Algorithms/Single-source shortest path/Dijkstra's Algorithm
  Compendium/Algorithms/Sorting/Heapsort
  Compendium/Algorithms/Sorting/Linear Sorting/Counting Sort
  Compendium/Algorithms/Sorting/Linear Sorting/Linear Sorting Abstract
  Compendium/Algorithms/Sorting/Mergesort
  Compendium/Algorithms/Sorting/Quicksort
  Compendium/Algorithms/Sorting/Topological Sort/Topological Sort Abstract
  Compendium/Data Structures/Graphs/Graphs Basics
  Compendium/Data Structures/Graphs/Trees/Binary Search Trees/Binary Search Trees
  Compendium/Data Structures/Graphs/Trees/Binary Search Trees/Red-black trees
  Compendium/Data Structures/Graphs/Trees/Heaps
  Compendium/Data Structures/Lists & Sets/Arrays & Lists
  Compendium/Data Structures/Lists & Sets/LinkedLists
  Compendium/Data Structures/Lists & Sets/Sets
  Compendium/Data Structures/Maps/Hashmaps and Dictionaries
  Compendium/Data Structures/Stacks & Queues/Stacks
  Compendium/Paradigms & Miscellaneous/Dynamic Programming/DP Basics
  Compendium/Paradigms & Miscellaneous/Dynamic Programming/Greedy Algorithms
  Compendium/Paradigms & Miscellaneous/Hashing
  Compendium/Paradigms & Miscellaneous/Loop Invariant
  Compendium/Paradigms & Miscellaneous/Polynomial and Nondeterministic Polynomial Problems (P and NP)
  Compendium/Paradigms & Miscellaneous/Time Complexity/Big O
  Compendium/Paradigms & Miscellaneous/Time Complexity/Master Theorems
  Compendium/Paradigms & Miscellaneous/Time Complexity/Recurrence Relations
  Compendium/README.md
Labels: EC Approved

#133 [HW][HW5] - Solutions w/ Explanations - [Christopher Oh]
  HW/HW 5/Problem 1.txt
  HW/HW 5/Problem 2.txt
  HW/HW 5/Problem Statement.txt
Labels: EC Approved

#134 [HW][HW4] - Time Complexity - [Christopher Oh]
  HW/HW 4/Insertion Sort.txt
  HW/HW 4/Matrix Mult.txt
  HW/HW 4/Problem Statement.txt
Labels: EC Approved

#149 [ENHANCEMENT][NOTES][SUMMARIES] - Transcribed and improved 'Brief Descriptions of Topo Sort, MST, SSP, Shortest Distance all Nodes Algorithms.pdf' - [Ryan Rajaie]
  Notes/Summaries/Heap representation, Kahn's, Prim's, Kruskal's, SSSP, ASSP algos.md
Labels: EC Approved

#152 [HW][HW10] - Plain English Approach - [Varshan Kumar]
  HW/HW10/Plain English Approach for Tree Traversal.md
Labels: EC Approved

#154 [Lab][Lab2] - [Hash Map Approach Pseudocode for Anagram Detection][Fnu Saad]
  Labs/Lab2/Pseudocode
Labels: EC Approved

#159 [HW][HW 7] - Two Pointer Approach Java - [Samson Xu]
  HW/HW 7/hw7.java
Labels: EC Approved

#161 [HW][HW12] - Plain English Approach [Anas Durrani]
  HW/HW12/PlainApproachHW12.txt
Labels: EC Approved

#162 [Labs][Lab4] - Special Case Iterative Approach Java [Anas Durrani]
  Labs/Lab4/Lab4_IterationSolution.java
Labels: EC Approved

#163 [Labs][Lab4] - Special Case Iterative Approach Python [Anas Durrani]
  Labs/Lab4/Lab4_IterationSolution.py
Labels: EC Approved

#165 [LABS][LAB6] - Alternate Python DFS Solution - [Varshan Kumar]
  Labs/Lab 6/lab6.py
Labels: EC Approved

#166 [LABS][LAB6] - Alternate Java DFS Solution - [Varshan Kumar]
  Labs/Lab 6/Lab6.java
Labels: EC Approved

#167 [HW][HW12] - [Optimized Solution For MST in Python] - [Varshan Kumar]
  HW/HW12/Prims_modified_solution.py
Labels: EC Approved

#168 [HW][HW12] - [Optimized Solution For MST in Java] - [Varshan Kumar]
  HW/HW12/Prims_modified_solution.java
Labels: EC Approved

#170 [HW][HW 7] Two Pointer Approach Python [Samson Xu]
  HW/HW 7/hw7_twopointer.py
Labels: EC Approved

#171 [HW][HW 7] Two Pointer Approach In Plain English [Samson Xu]
  HW/HW 7/hw7_twopointer_english.md
Labels: EC Approved

#172 [HW][HW 7] Two Pointer Approach Pseudocode [Samson Xu]
  HW/HW 7/HW7_PseudocodeTwoPointer.md
Labels: EC Approved

#173 [Labs][Lab 5] Python DFS Solution [Samson Xu]
  Labs/Lab5/lab5_dfs.py
Labels: EC Approved

#175 [HW][HW 1] Java Two Pointer Improved [Samson Xu]
  HW/HW1/hw1_twopointer_improved.java
Labels: EC Approved

#176 [HW][HW 1] Python Reverse Improved [Samson Xu]
  HW/HW1/hw1_revstring_improved.py
Labels: EC Approved

#177 [HW][HW 1] Improved Solutions Plain English [Samson Xu]
  HW/HW1/hw1_improved_appraoches.md
Labels: EC Approved

#178 [COMPENDIUM][A*] Added A* section to Compendium [Ryan Rajaie]
  Compendium/Algorithms/Single-source shortest path/A*
  Compendium/Algorithms/Single-source shortest path/A*.md
Labels: EC Approved

#179 [COMPENDIUM][HASHING] Added hashing to Compendium [Ryan Rajaie]
  Compendium/Paradigms & Miscellaneous/Hashing
  Compendium/Paradigms & Miscellaneous/Hashing.md
Labels: EC Approved

#180 [Labs][Lab8] Psuedocode for Lab 8
  Labs/Lab8/Psuedocode_Lab8.txt
Labels: EC Approved

#182 [Labs][Lab7] Floyd-Warshall Java Solution
  Labs/Lab 7/Lab7.java
Labels: EC Approved

#181 [Labs][Lab6] Java Queue Solution [Anas Durrani]
  Labs/Lab 6/Lab6QueueSolution.java
Labels: change requested, EC Approved

#184 [Labs][Lab7] Plain English Approach [Anas Durrani]
  Labs/Lab 7/PlainEnglishApproach_Lab7.txt
Labels: change requested, EC Approved

#185 [Labs][Lab7] Psuedocode Solution [Anas Durrani]
  Labs/Lab 7/Psuedocode_Lab7.txt
Labels: change requested, EC Approved

#186 [Compendium][All-pairs_Shortest_Path] Floyd-Warshall Article [Anas Durrani]
  Compendium/Algorithms/All-pairs shortest path/Floyd-Warshall Algorithm
  Compendium/Algorithms/All-pairs shortest path/Floyd-Warshall Algorithm.md
Labels: change requested, EC Approved

#187 [Compendium][Big O] Added Time complexity and Best, Worst, Average case sections to the compendium [Ryan Rajaie]
  Compendium/Paradigms & Miscellaneous/Time Complexity/Asymptotic Notation and Cases.md
  Compendium/Paradigms & Miscellaneous/Time Complexity/Big O
Labels: EC Approved

#188 [EC][Topological Sorting and other party tricks] - Java Topological Kahn - [Alejandro Pacheco]
  Extra Credit/Bonus Questions - Topological Sorting and other party tricks/TopologicalSortKahn.java
Labels: EC Approved

#191 [EC][Topological Sorting and other party tricks] - Explaining Example - [Alejandro Pacheco]
  Extra Credit/Bonus Questions - Topological Sorting and other party tricks/My findings.md
Labels: EC Approved

#193 [Compendium][Master's Theorem] Filled section for Master Theorem topic [Ryan Rajaie]
  Compendium/Paradigms & Miscellaneous/Time Complexity/Master Theorems
  Compendium/Paradigms & Miscellaneous/Time Complexity/Master Theorems.md
Labels: EC Approved

#194 [Labs][Lab 6] - Pseudocode Kahn Solution - [Alejandro Pacheco]
  Labs/Lab6/Lab6 PseudocodeKahn.txt
Labels: EC Approved

#195 [Labs][Lab 5] - Pseudocode Recursive Solution - [Alejandro Pacheco]
  Labs/Lab5/Lab5_recursionPseudo.txt
Labels: EC Approved

#196 [Compendium][Loop Invariant] Added loop invariant to compendium [Ryan Rajaie]
  Compendium/Paradigms & Miscellaneous/Loop Invariant
  Compendium/Paradigms & Miscellaneous/Loop Invariant.md
Labels: EC Approved

#197 [EC][Bonus Questions - Third lightbulb's the charm] - Java Dynamic Programming Solution - [Alisha Sinha]
  Extra Credit/Bonus Questions - Third lightbulb's the charm/Fibo.java
Labels: EC Approved

#198 [Compendium][RB Trees] Added Red-Black trees to Compendium [Ryan Rajaie]
  Compendium/Data Structures/Graphs/Trees/Binary Search Trees/Red-black trees
  Compendium/Data Structures/Graphs/Trees/Binary Search Trees/Red-black trees.md
Labels: EC Approved

#199 [EC][Bonus Questions - Third lightbulb's the charm] - Python Dynamic Programing Solution - [Alisha Sinha]
  Extra Credit/Bonus Questions - Third lightbulb's the charm/Fibo.py
Labels: EC Approved

#200 [COMPENDIUM][READ ME] Added formatting requirements to the Readme [Ryan Rajaie]
  Compendium/README.md
Labels: EC Approved

#202 [NOTES] - Introduction to graphs - [Sarthak Sethi ]
  Notes/Summaries/Introduction to Graphs.pdf
Labels: EC Approved

#216 [Compendium][Queues] Added queues [Ryan Rajaie]
  Compendium/Data Structures/Stacks & Queues/Queues.md
Labels: EC Approved

#217 [Compendium][Stacks] Added stacks content [Ryan Rajaie]
  Compendium/Data Structures/Stacks & Queues/Stacks
  Compendium/Data Structures/Stacks & Queues/Stacks.md
Labels: EC Approved

#218 [Compendium][Hashmaps & Dictionaries] Added content for Hashmaps and Dictionaries [Ryan Rajaie]
  Compendium/Data Structures/Maps/Hashmaps and Dictionaries
  Compendium/Data Structures/Maps/Hashmaps and Dictionaries.md
Labels: EC Approved

#219 [Compendium][Graphs Basics] Added content for graphs basics [Ryan Rajaie]
  Compendium/Data Structures/Graphs/Graphs Basics
  Compendium/Data Structures/Graphs/Graphs Basics.md
Labels: EC Approved

#220 [Compendium][Heaps] Added content for heaps [Ryan Rajaie]
  Compendium/Data Structures/Graphs/Trees/Heaps
  Compendium/Data Structures/Graphs/Trees/Heaps.md
Labels: EC Approved

#221 [Compendium][Heapsort] Added content for heapsort [Ryan Rajaie]
  Compendium/Algorithms/Sorting/Heapsort
  Compendium/Algorithms/Sorting/Heapsort.md
Labels: EC Approved

#222 [Compendium][Bellman-Ford] Added content for Bellman-Ford [Ryan Rajaie]
  Compendium/Algorithms/Single-source shortest path/Bellman-Ford Algorithm
  Compendium/Algorithms/Single-source shortest path/Bellman-Ford Algorithm.md
Labels: EC Approved

#223 [Compendium][MST Abstract] Added intuition for MST problem [Ryan Rajaie]
  Compendium/Algorithms/Minimum Spanning Tree (MST)/Boruvka's Algorithm
  Compendium/Algorithms/Minimum Spanning Tree (MST)/MST Abstract.md
Labels: EC Approved

#224 [Compendium][Prim's Algorithm] Added content for Prim's [Ryan Rajaie]
  Compendium/Algorithms/Minimum Spanning Tree (MST)/Prim's Algorithm
  Compendium/Algorithms/Minimum Spanning Tree (MST)/Prim's Algorithm.md
Labels: EC Approved

#225 [Compendium][Kruskal's Algorithm] Added content for Kruskal's [Ryan Rajaie]
  Compendium/Algorithms/Minimum Spanning Tree (MST)/Kruskal's Algorithm
Labels: EC Approved

#226 [Compendium][Johnson's Algorithm] Added content for Johnson's Algorithm [Ryan Rajaie]
  Compendium/Algorithms/All-pairs shortest path/Johnson's Algorithm
  Compendium/Algorithms/All-pairs shortest path/Johnson's Algorithm.md
Labels: EC Approved

#227 [Compendium][Bread-first Search] Added content for BFS [Ryan Rajaie]
  Compendium/Algorithms/Graph Traversal/Breadth-First Search
  Compendium/Algorithms/Graph Traversal/Breadth-First Search.md
Labels: EC Approved

#228 [Compendium][Depth-first Search] Added content for DFS [Ryan Rajaie]
  Compendium/Algorithms/Graph Traversal/Depth-First Search
  Compendium/Algorithms/Graph Traversal/Depth-First Search.md
Labels: EC Approved

#229 [Compendium][Topological Sort] Added content for topo sort and touched up file structure [Ryan Rajaie]
  Compendium/Algorithms/Sorting/Topological Sort.md
  Compendium/Algorithms/Sorting/Topological Sort/Topological Sort Abstract
Labels: EC Approved

#230 [Compendium][Mergesort] Added content to Mergesort [Ryan Rajaie]
  Compendium/Algorithms/Sorting/Mergesort
  Compendium/Algorithms/Sorting/Mergesort.md
Labels: EC Approved

#231 [Compendium][Dijkstra Algorithm] -Added Information on Dijkstra Algorithm- [Sarthak Sethi]
  Compendium/Algorithms/Single-source shortest path/Dijkstra's Algorithm
  Compendium/Algorithms/Single-source shortest path/Dijkstra's Algorithm.md
Labels: EC Approved

#232 [Compendium][Quicksort Algorithm] -Added Information on Quicksort Algorithm- [Sarthak Sethi]
  Compendium/Algorithms/Sorting/Quicksort
  Compendium/Algorithms/Sorting/Quicksort.md
Labels: EC Approved

#235 [Compendium][P and NP] Added content for P and NP problems [Ryan Rajaie]
  Compendium/Paradigms & Miscellaneous/Polynomial and Nondeterministic Polynomial Problems (P and NP)
  Compendium/Paradigms & Miscellaneous/Polynomial and Nondeterministic Polynomial Problems (P and NP).md
Labels: EC Approved

#236 [Compendium][DP Basics] Added content to DP basics [Ryan Rajaie]
  Compendium/Paradigms & Miscellaneous/Dynamic Programming/DP Basics
  Compendium/Paradigms & Miscellaneous/Dynamic Programming/DP Basics.md
Labels: EC Approved

#237 [NOTES] - Condensed Semester Notes - [Justin Nguyen]
  Notes/Condensed Notes/CS 146 Spring 2024 Condensed Notes.pdf
  Notes/Condensed Notes/empty.md
Labels: EC Approved

#238 [COMPENDIUM][TREES] Added Binary Search Trees Entry [Anas Durrani]
  Compendium/Data Structures/Graphs/Trees/Binary Search Trees/Binary Search Trees
  Compendium/Data Structures/Graphs/Trees/Binary Search Trees/Binary Search Trees.md
Labels: EC Approved

#239 [Compendium][Sets] Added content for sets [Ryan Rajaie]
  Compendium/Data Structures/Lists & Sets/Sets
  Compendium/Data Structures/Lists & Sets/Sets.md
Labels: EC Approved

#242 [HW][HW8] HashSet Solution in Java [Samson Xu]
  HW/HW8/hw8HashSet.java
Labels: EC Approved

#243 [HW][HW8] HashSet Solution in Python [Samson Xu]
  HW/HW8/hw8HashSet.py
Labels: EC Approved

#244 [HW][HW8] HashSet Solution Pseudocode [Samson Xu]
  HW/HW8/hw8HashSet Pseudo.md
Labels: EC Approved

#245 [HW][HW8] HashSet Plain English Approach [Samson Xu]
  HW/HW8/hw8HashSetPlainEng
Labels: EC Approved

#247 [HW][HW10] Java Queue Solution [Anas Durrani]
  HW/HW10/HW10Queue.java
Labels: EC Approved

#249 [Labs][Lab7] Lab 7 Dijkstras Solution Java [Anas Durrani]
  Labs/Lab7/lab7Dijkstras.java
Labels: EC Approved

#250 [Labs][Lab7] Lab 7 Dijkstras Solution Python [Anas Durrani]
  Labs/Lab7/lab7dijsktras.py
Labels: EC Approved

#251 [HW][HW9] - Java/python BST lowest common ancestor approach - [Aman Kaur]
  HW/HW9/approach
Labels: EC Approved

#253 [NOTES-SUMMARIES] - Insertion sort - [Aman Kaur]
  Notes/Summaries/insertionsort
Labels: EC Approved

#259 [NOTES- summaries] - QuickSort - [Aman Kaur]
  Notes/Summaries/Quicksort
Labels: EC Approved

#261 [Labs][Lab 1] - Python Hashmap (Updated) Solution - [Prasham Sheth]
  Labs/Lab1/lab1.py
Labels: EC Approved

#263 [Labs][Lab 1] - Java Hashmap (Updated) Solution - [Prasham Sheth]
  Labs/Lab1/lab1.java
Labels: EC Approved

#267 [HW][HW6] - Python Bruteforce Solution - [Prasham Sheth]
  HW/HW6/HW6Bruteforce.py
Labels: EC Approved

#269 [HW][HW6] - Bruteforce in Plain English - [Prasham Sheth]
  HW/HW6/HW6BruteforceEnglish
Labels: EC Approved

#270 Create [NOTES] - Making Google Maps notes - [Alisha Sinha].pdf
  Notes/Full Length Notes/Making Google Maps/[NOTES] - Making Google Maps notes - [Alisha Sinha].pdf
Labels: EC Approved

#272 Create [NOTES] - Minimum Spanning Treenotes - [Alisha Sinha].pdf
  Notes/Full Length Notes/Minimum Spanning Trees/[NOTES] - Minimum Spanning Treenotes - [Alisha Sinha].pdf
Labels: EC Approved

#273 [Hw][Hw1]-[PseudoCode][Fnu Saad]
  HW/HW1/[Hw][Hw1]-[PseudoCode][Fnu Saad]
Labels: EC Approved

#275 [Hw][Hw2]-[PseudoCode ][Fnu Saad]
  HW/HW2/[Hw][Hw2]-[PseudoCode ][Fnu Saad]
Labels: EC Approved

#276 [Hw][Hw5]-[Analyzing Recurrence Relations and Time Complexity …
  HW/HW 5/[Hw][Hw5]-[Analyzing Recurrence Relations and Time Complexity ][Fnu Saad]
Labels: duplicate

#277 [NOTES -Summaries] - SelectionSort- [Aman Kaur]
  Notes/Summaries/SelectionSort
Labels: EC Approved

#278 Create [NOTES] - Other Dynamic Situation Being greedy isn't always ba…
  Notes/Full Length Notes/Other Dynamic Situation Being greedy isn't always bad/[NOTES] - Other Dynamic Situation Being greedy isn't always bad notes- [Alisha Sinha].pdf
Labels: EC Approved

#279 [NOTES -Summaries ] -BubbleSort - [Aman Kaur]
  Notes/Summaries/BubbleSort
Labels: EC Approved

#280 Create [NOTES-Summaries] - Time Complexities for Algorithms - [Alisha Sinha].pdf
  Notes/Summaries/[NOTES] - Time Complexities for Algorithms  - [Alisha Sinha].pdf
Labels: EC Approved

#281 [HW][HW9] - Python Iterative Solution - [Prasham Sheth]
  HW/HW9/HW9Iterative.py
Labels: EC Approved

#282 [HW][HW9] - Java Iterative Solution - [Prasham Sheth]
  HW/HW9/HW9Iterative.java
Labels: EC Approved

#283 [HW][HW9] - Iterative Approach in English - [Prasham Sheth]
  HW/HW9/PlainEnglishIterative.md
Labels: EC Approved

#286 Create Create [NOTES] - Everything Everywhere All At Once - [Alisha S…
  Notes/Full Length Notes/Everything Everywhere All At Once/Create [NOTES] - Everything Everywhere All At Once - [Alisha Sinha].pdf
Labels: EC Approved

#287 [HW][HW10] - Java BFS solution - [Ryan Shim]
  HW/HW10/HW10bfs.java
Labels: duplicate

#297 [LABS][LAB2] - approach - [Aman Kaur]
  Labs/Lab1/approach
Labels: EC Approved

#306 [NOTES] - How many people do you need to screw in infinite lightbulbs- [Aman Kaur]
  Notes/Full Length Notes/How many people do you need to screw in infinite lightbulbs/summary
Labels: EC Approved

#310 [NOTES] - Seeing the Forest for the tree - [Aman Kaur]
  Notes/Full Length Notes/Seeing the forest for the trees/notes
Labels: EC Approved
